ARG KEYCLOAK_VERSION=latest
ARG HTTP_PORT=8443
ARG KEYCLOAK_ADMIN=admin
ARG KEYCLOAK_ADMIN_PASSWORD=admin
ARG KC_HEALTH_ENABLED=true
ARG KC_METRICS_ENABLED=true
ARG KC_DB=postgres
ARG KC_DB_URL=jdbc:postgresql://localhost:5432/keycloak
ARG KC_DB_USERNAME=keycloak
ARG KC_DB_PASSWORD=password
ARG KC_HOSTNAME=localhost

FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}

ENV KC_HEALTH_ENABLED=${KC_HEALTH_ENABLED}
ENV KC_METRICS_ENABLED=${KC_METRICS_ENABLED}
ENV KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
ENV KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}

ENV KC_DB=${KC_DB}
ENV KC_DB_URL=${KC_DB_URL}
ENV KC_DB_USERNAME=${KC_DB_USERNAME}
ENV KC_DB_PASSWORD=${KC_DB_PASSWORD}
ENV KC_HOSTNAME=${KC_HOSTNAME}

EXPOSE ${HTTP_PORT}

CMD ["start-dev", "--http-port=${HTTP_PORT}"]
